### ISSUE TITLE
is ws_client broken?

### ISSUE THREAD

**Issue by MatzFan** [boazsegev/GRHttp#2]
Your latest commit says as much and when I run your 'more complete' example client code (in IRB) I get this:
```
GRHttp.joinE, [2015-09-01T14:45:42.767372 #18395] ERROR -- : No #on_message handler defined! please pass a block or define an #on_message handler! (RuntimeError)
/Users/me/.rvm/gems/ruby-2.2.2/gems/grhttp-0.0.23/lib/grhttp/ws_client.rb:145:in `connect'
/Users/me/.rvm/gems/ruby-2.2.2/gems/grhttp-0.0.23/lib/grhttp/api.rb:37:in `ws_connect'
(irb):39:in `block in irb_binding'
/Users/me/.rvm/gems/ruby-2.2.2/gems/greactor-0.0.15/lib/greactor/events.rb:57:in `call'
/Users/me/.rvm/gems/ruby-2.2.2/gems/greactor-0.0.15/lib/greactor/events.rb:57:in `do_job'
/Users/me/.rvm/gems/ruby-2.2.2/gems/greactor-0.0.15/lib/greactor/engine.rb:168:in `run'
/Users/me/.rvm/gems/ruby-2.2.2/gems/greactor-0.0.15/lib/greactor/engine.rb:106:in `block (2 levels) in create_workers'
```
Otherwise basic client example is fine and code looks v. promising as EM alternative :smile:

Using gem v0.0.23

**Comment by boazsegev** [comment]
`ws_client` is broken for the upcoming version. It will be fixed before the upcoming version is released.

The API has an issue with the current `GRHttp.ws_connect`. There's an accidental assignment that clears the hash passed.

For now, use `GRHttp::WSClient.connect` instead.

I'm on my way to Burning Man and will be in the desert for a week without my laptop... So if something comes up, it might take me a bit, but I'll get on it the moment I'm back.

**Comment by MatzFan** [comment]
Cool, thanks for the update & have a blast!
